version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: discord-bot-prod
    restart: unless-stopped
    env_file:
      - bot/.env.prod
    depends_on:
      - mongodb
    networks:
      - bot-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  mongodb:
    image: mongo:latest
    container_name: mongodb-prod
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    networks:
      - bot-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  mongodb_data:
    driver: local

networks:
  bot-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16 